### ISSUE TITLE
Meta: self-host monofo to reduce build time

### ISSUE THREAD

**Issue by dominics** [vital-software/monofo#271]
- [x] #272 Add support for excluding directories from the pipeline search, or giving a base directory
    ![image](https://user-images.githubusercontent.com/97427/142967216-00bcf254-d3e2-43d7-a4f7-c44524bb352d.png)
- [x] Split the pipeline files into: node-modules, typescript, test, release
- [x] Replace docker containers with volumes
